spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/edulearn

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  security:
    expose-swagger: true

auth:
  password-reset:
    debug-return-token: true
